### ISSUE TITLE
Line breaks cause lists to be cut off 

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [marhkb/symphony#80]
Very long image names can cause line breaks that cause the image and container lists to be cut off prematurely.

![image](https://user-images.githubusercontent.com/15961647/159135345-27fe300e-46a2-4c83-b227-1371bae5a9a2.png)
![image](https://user-images.githubusercontent.com/15961647/159135371-3f1f8701-8988-45c7-a359-1abd6176215a.png)

**Comment by marhkb** [comment]
Thank you very much for reporting this. I opened a PR that will hopefully fix this.
Would be great if you could give feedback

**Comment by SoMuchForSubtlety** [comment]
I tested the build from #83 and the issue is no longer present. Thanks for the fast fix!
