### ISSUE TITLE
Adding new translations

### ISSUE THREAD

**Issue by Gert-dev** [marhkb/symphony#81]
Hello

If I wanted to add a new translation, such as Dutch, which is not present yet, can I just translate one of the existing PO files and create a PR with the new PO file? Or will that cause problems with Weblate as they are generated? I can't seem to create a new translation for Dutch through Weblate because I do not have permissions for it.

Thanks!

**Comment by marhkb** [comment]
Oh no, how could I forget Dutch. :stuck_out_tongue_winking_eye:
Joking aside, yes your approach should work. You should also add the abbreviation to the file `LINGUAS`, so that the po file can always be updated.
